FROM postgres:17.2

# Time ZoneAc
ENV TZ Asia/Tokyo

# Language

ENV POSTGRES_ROOT_USER postgres
ENV POSTGRES_USER username
ENV POSTGRES_PASSWORD password
ENV POSTGRES_DB catalog-db

COPY init.sql /docker-entrypoint-initdb.d/
